name: Triton
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - contourpy=1.3.3=py313h7037e92_2
  - cycler=0.12.1=pyhd8ed1ab_1
  - fonttools=4.60.0=py313h3dea7bd_0
  - freetype=2.14.1=ha770c72_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py313hc8edb43_1
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - lerc=4.0.0=h0aef613_1
  - libblas=3.9.0=35_h4a7cf45_openblas
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcblas=3.9.0=35_h0358290_openblas
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.24=h86f0d12_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgomp=15.1.0=h767d61c_5
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=35_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libmpdec=4.0.0=hb9d3cd8_0
  - libnghttp2=1.67.0=had1ee68_0
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libpng=1.6.50=h421ea60_1
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libtiff=4.7.0=h8261f1e_6
  - libuuid=2.41.1=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.6=py313h683a580_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.3=py313hf6604e3_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py313h08cd8bf_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.3.0=py313hf46931b_2
  - pip=25.2=pyh145f28c_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyparsing=3.2.4=pyhcf101f3_0
  - pysam=0.23.3=py313h7c062c9_1
  - python=3.13.7=h2b335a9_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=8_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - scipy=1.16.2=py313h11c21cd_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - six=1.17.0=pyhe01879c_1
  - statsmodels=0.14.5=py313ha014f3b_0
  - tk=8.6.13=noxft_hd72426e_102
  - tzdata=2025b=h78e105d_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - zstd=1.5.7=hb8e6e7a_2

prefix: "/home/rpatton/.local/share/mamba/envs/Triton"
