samples:
  HD2:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/HD2.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/HD2.GC_bias.txt
  HD45:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/HD45.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/HD45.GC_bias.txt
  HD46:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/HD46.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/HD46.GC_bias.txt
  KP65194:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65194.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65194.GC_bias.txt
  KP65195:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65195.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65195.GC_bias.txt
  KP65197:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65197.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65197.GC_bias.txt
  KP65198:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65198.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65198.GC_bias.txt
  KP65225:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65225.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65225.GC_bias.txt
  KP65231:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/KP65231.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/KP65231.GC_bias.txt
  NPH001:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH001.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH001.GC_bias.txt
  NPH002:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH002.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH002.GC_bias.txt
  NPH003:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH003.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH003.GC_bias.txt
  NPH004:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH004.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH004.GC_bias.txt
  NPH005:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH005.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH005.GC_bias.txt
  NPH006:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH006.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH006.GC_bias.txt
  NPH007:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH007.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH007.GC_bias.txt
  NPH008:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH008.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH008.GC_bias.txt
  NPH009:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH009.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH009.GC_bias.txt
  NPH010:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH010.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH010.GC_bias.txt
  NPH011:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH011.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH011.GC_bias.txt
  NPH012:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH012.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH012.GC_bias.txt
  NPH013:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH013.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH013.GC_bias.txt
  NPH014:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH014.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH014.GC_bias.txt
  NPH015:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH015.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH015.GC_bias.txt
  NPH016:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH016.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH016.GC_bias.txt
  NPH017:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH017.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH017.GC_bias.txt
  NPH018:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH018.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH018.GC_bias.txt
  NPH023:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH023.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH023.GC_bias.txt
  NPH026:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH026.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH026.GC_bias.txt
  NPH033:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH033.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH033.GC_bias.txt
  NPH034:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH034.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH034.GC_bias.txt
  NPH035:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH035.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH035.GC_bias.txt
  NPH036:
    bam: /fh/fast/ha_g/user/rpatton/HD_data/bams/NPH036.bam
    GC_bias: /fh/fast/ha_g/user/rpatton/HD_data/GC-Correction/results/repeat_masker.mapable.k50.Umap.hg38/GC_bias/NPH036.GC_bias.txt
